select DEVICENAME as Name, ADDRESS, DEVICEID, USERNAME, PASSWORD, CAST(ISNULL(DEVICEACTIVE, 'True') as bit) as DEVICEACTIVE, row_number() OVER (order by DEVICENAME) as Id from vwDEVICES where DEVICENAME like '%48'

select * from vwDEVICES D
inner join DEVICEDETAILS DD on DD.DEVICE = D.DEVICENAME and DD.PROPERTYNAME not in ('ADDRESS','DEVICEID','USERNAME','PASSWORD','DEVICEACTIVE','PHONE1')
where D.DEVICENAME = '1 Haus Zeller Oberdorf'


select D.DEVICENAME as Name, D.ADDRESS, D.DEVICEID, D.USERNAME, D.PASSWORD, CAST(ISNULL(D.DEVICEACTIVE, 'True') as bit) as DEVICEACTIVE, row_number() OVER (order by DEVICENAME) as Id, DD.PROPERTYNAME as AttrName, DD.PROPERTYVALUE as AttrValue 
from vwDEVICES D
inner join DEVICEDETAILS DD on DD.DEVICE = D.DEVICENAME and DD.PROPERTYNAME not in ('ADDRESS','DEVICEID','USERNAME','PASSWORD','DEVICEACTIVE','PHONE1')

DD.PROPERTYNAME as AttrName, DD.PROPERTYVALUE as AttrValue

SELECT result.* FROM(select D.DEVICENAME as Name, D.ADDRESS, D.DEVICEID, D.USERNAME, D.PASSWORD, CAST(ISNULL(D.DEVICEACTIVE, 'True') as bit) as DEVICEACTIVE, row_number() OVER (order by DEVICENAME) as Id from vwDEVICES D where D.DEVICENAME like '%') AS result 
inner join DEVICEDETAILS DD on DD.DEVICE = Name and DD.PROPERTYNAME not in ('ADDRESS','DEVICEID','USERNAME','PASSWORD','DEVICEACTIVE','PHONE1')
WHERE Id > 20 AND Id <= 40

select DEVICE as AttrParent, PROPERTYNAME as AttrName, PROPERTYVALUE as AttrValue from DEVICEDETAILS where DEVICE = '1 Haus Zeller Oberdorf' and PROPERTYNAME = 'ADDRESS'

select DEVICE as AttrParent, PROPERTYNAME as AttrName, PROPERTYVALUE as AttrValue from DEVICEDETAILS where DEVICE = '1 Haus Zeller Oberdorf' and PROPERTYNAME = 'ADDRESS'